image: docker:latest

services:
  - docker:dind

stages:
  - lint
  - test
  - coverage
  - build
  - deploy

# Étape lint
lint:
  script:
    - npm install
    - npx eslint "src/**/*.js" -f json -o lint-es.json
    - npx htmlhint "src/**/*.html" --format json > lint-html.json
    - npx stylelint "src/**/*.{css,scss}" -f json > lint-style.json
    - jq -s add lint-es.json lint-html.json lint-style.json > lint.json
  artifacts:
    when: always
    paths:
      - lint.json

# Étape tests
test:
  script:
    - npm install
    - npm test -- --reporter mocha-junit-reporter --reporter-options mochaFile=test-results.xml
  artifacts:
    when: always
    reports:
      junit:
        - test-results.xml
    paths:
      - test-results.xml

# Étape couverture
coverage:
  script:
    - pip install coverage pytest
    - coverage run -m pytest
    - coverage report
    - coverage html
    - coverage xml
    - mv htmlcov/index.html coverage.html
  artifacts:
    when: always
    paths:
      - coverage.html

# Étape build (construction de l'image Docker)
build:
  script:
    - docker build -t web-test .
  needs:
    - lint
    - test
    - coverage

# Étape push vers Docker Hub
push_to_dockerhub:
  script:
    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
    - docker tag web-test $DOCKER_USERNAME/web-test:latest
    - docker push $DOCKER_USERNAME/web-test:latest
  needs:
    - build
  only:
    - master

# Étape déploiement sur le serveur
deploy:
  script:
    - docker run --rm -v $(pwd)/deploy.sh:/deploy.sh $DOCKER_USERNAME/web-test /bin/sh /deploy.sh
  needs:
    - push_to_dockerhub
  only:
    - master