image: node:18

stages:
  - lint
  - test
  - build

lint:
  stage: lint
  script:
    - npm install
    - if [ -z "$(find src -type f)" ]; then echo "No files in src, skipping lint"; else
      npx eslint "src/**/*.js" -f json -o lint-es.json &&
      npx htmlhint "src/**/*.html" --format json > lint-html.json &&
      npx stylelint "src/**/*.{css,scss}" -f json > lint-style.json &&
      jq -s add lint-es.json lint-html.json lint-style.json > lint.json;
      fi
  artifacts:
    when: always
    paths:
      - lint.json

test:
  stage: test
  script:
    - npm install
    - if [ -z "$(find src -type f)" ]; then echo "No files in src, skipping tests"; else
      npm test -- --reporter mocha-junit-reporter --reporter-options mochaFile=test-results.xml;
      fi
  artifacts:
    when: always
    reports:
      junit:
        - test-results.xml
    paths:
      - test-results.xml

build:
  image: docker
  stage: build
  needs:
    - test
  script:
    - docker build -t web-test .